### ISSUE TITLE
您好，代码复现时出现了一些问题，能请教一下吗？运行的数据集是ohsumed

### ISSUE THREAD

**Issue by Jungle-liu** [ZeroRin/BertGCN#3]
按照readme里的运行方式，因为配置问题，将finetune_bert.py的batch_size改为了32，finetune_bert.py能够成功运行。将train_bert_gcn.py中的第一个batch_size改为了16，将updata_feature中的batch_size改为了256，运行时，运行到了13个epoch中断，出现以下错误：
Epoch: 13  Train acc: 0.8865 loss: 0.2449  Val acc: 0.6627 loss: 1.4258  Test acc: 0.7099 loss: 1.3214
Current run is terminating due to exception: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity.
Engine run is terminating due to exception: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity.
Traceback (most recent call last):
  File "E:/BertGCN-main/train_bert_gcn.py", line 278, in <module>
    trainer.run(idx_loader, max_epochs=nb_epochs)
  File "D:\Anaconda3\envs\BertGCN\lib\site-packages\ignite\engine\engine.py", line 691, in run
    return self._internal_run()
  File "D:\Anaconda3\envs\BertGCN\lib\site-packages\ignite\engine\engine.py", line 762, in _internal_run
    self._handle_exception(e)
  File "D:\Anaconda3\envs\BertGCN\lib\site-packages\ignite\engine\engine.py", line 467, in _handle_exception
    raise e
  File "D:\Anaconda3\envs\BertGCN\lib\site-packages\ignite\engine\engine.py", line 730, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "D:\Anaconda3\envs\BertGCN\lib\site-packages\ignite\engine\engine.py", line 828, in _run_once_on_dataset
    self._handle_exception(e)
  File "D:\Anaconda3\envs\BertGCN\lib\site-packages\ignite\engine\engine.py", line 467, in _handle_exception
    raise e
  File "D:\Anaconda3\envs\BertGCN\lib\site-packages\ignite\engine\engine.py", line 811, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "E:/BertGCN-main/train_bert_gcn.py", line 208, in train_step
    y_pred = y_pred.argmax(axis=1).detach().cpu()
RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity

进程已结束，退出代码 1

**Comment by ZeroRin** [comment]
这个错误我之前遇到过，是因为一个batch里采到的恰好都是无标注的节点。当时应该是修复了的，可能是我在版本管理上出了点问题，之后更新一下

**Comment by ZeroRin** [comment]
应该已经修好了，可以再试试。（这个部分是之前用来每个iteration实时显示训练acc留的，其实可能直接删掉也没问题）

**Comment by Ghadah22** [comment]
hello, when I run the code I found those error 
(pytorch) ghadah@Ghadahs-Air BertGCN-main 2 % /Users/ghadah/opt/anaconda3/envs/BertGCN/bin/python "/Users/ghadah/Downloads/BertGCN-main 2/finetu
ne_bert.py"
arguments:
Namespace(max_length=128, batch_size=128, nb_epochs=60, bert_lr=0.0001, dataset='20ng', bert_init='roberta-base', checkpoint_dir=None)
checkpoints will be saved in ./checkpoint/roberta-base_20ng
Traceback (most recent call last):
  File "/Users/ghadah/Downloads/BertGCN-main 2/finetune_bert.py", line 63, in <module>
    adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask, train_size, test_size = load_corpus(dataset)
  File "/Users/ghadah/Downloads/BertGCN-main 2/utils/utils.py", line 141, in load_corpus
    with open("data/ind.{}.{}".format(dataset_str, names[i]), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ind.20ng.x'
(pytorch) ghadah@Ghadahs-Air BertGCN-main 2 % 

File "/Users/ghadah/Downloads/BertGCN-main 2/checkpoint/roberta-base_20ng/finetune_bert.py", line 15, in <module>
    from model import BertClassifier
ModuleNotFoundError: No module named 'model'
(pytorch) ghadah@Ghadahs-Air BertGCN-main 2 %
